name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    services:
      ssh-server:
        image: lscr.io/linuxserver/openssh-server
        # docs: https://hub.docker.com/r/linuxserver/openssh-server
        ports:
          - 2222:2222
        env:
          USER_NAME: fred
          USER_PASSWORD: flipl5s
          PASSWORD_ACCESS: true
    timeout-minutes: 15
    strategy:
      matrix:
        image: ["swift:6.0"]

    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint
      run: swift package lint-source-code
    - name: Test
      run: |
        swift test --enable-code-coverage
      env:
        SSH_HOST: ssh-server
        SSH_PORT: 2222
        SSH_USERNAME: fred
        SSH_PASSWORD: flipl5s
    - name: Convert coverage files
      run: |
        llvm-cov export --format="lcov" \
          --instr-profile .build/debug/codecov/default.profdata \
          -ignore-filename-regex="\/Tests\/" \
          -ignore-filename-regex="\/Benchmarks\/" \
          .build/debug/FormicPackageTests.xctest > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: info.lcov
